spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password: 0829
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  # create: 애플리케이션 실행 시점에 테이블 drop, 다시 생성
    properties:
      hibernate:
        #show_sql: true  # System.out 에 하이버네이트 실행 SQL을 남김
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug  # logger를 통해 하이버네이트 실행 SQL을 남김 (주의: SQL 대문자여야함)
    org.hibernate.orm.jdbc.bind: trace # SQL 실행 파라미터를 로그로 남김